"""
signals/signal_generator.py
==============================
Multi-strategy decision engine for the AntiGravity Gold Bot.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
PIPELINE OVERVIEW  (updated — multi-strategy)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Raw OHLCV data
     │
     ▼
┌─────────────────────────────────────────────────────────────┐
│  SignalGenerator.generate(df_h1, df_m15, account_balance)   │
│                                                              │
│  Step 1 — Pre-scan filters                                   │
│    Session / Volatility / News — hard block if all fail      │
│                                                              │
│  Step 2 — Shared context (runs ONCE per cycle)               │
│    2a. Trend context   — TrendDetector(df_h1)                │
│    2b. Market regime   — MarketRegimeClassifier(df_h1)       │
│    2c. Liquidity sweep — LiquiditySweepDetector(df_m15)      │
│                                                              │
│  Step 3 — Run strategies IN PARALLEL (independent verdicts)  │
│    Strategy A: TREND STRATEGY                                │
│      Uses EMA 50/200, slope, strength → BUY/SELL/NEUTRAL     │
│    Strategy B: SMART MONEY (SMC) STRATEGY                    │
│      OB / FVG / BOS / CHoCH / Liq pool scan → TradeIdeas    │
│    Strategy C: LIQUIDITY SWEEP STRATEGY                      │
│      Detects stop-hunt events → BUY/SELL/NEUTRAL             │
│                                                              │
│  Step 4 — Confluence scoring                                 │
│    Count how many strategies agree on direction.             │
│    Agreement → confidence BOOST.                             │
│    Conflict  → signal REJECTED immediately.                  │
│                                                              │
│          0 agree → REJECTED (no actionable setup)            │
│          1 agrees → LOW confidence (may not pass threshold)  │
│          2 agree  → +0.08 confluence boost                   │
│          3 agree  → +0.15 confluence boost                   │
│                                                              │
│  Step 5 — Per-idea validation gates                          │
│    5a. Gate: news blackout  (hard reject)                    │
│    5b. Gate: trend alignment                                 │
│    5c. Gate: regime suitability                              │
│    5d. Confidence re-scoring (session+vol+liq+OB/FVG)       │
│    5e. Gate: minimum confidence threshold                    │
│    5f. Position sizing                                       │
│    5g. Gate: R:R threshold                                   │
│    5h. Assemble TradingSignal                                │
│                                                              │
│  Step 6 — Daily signal cap                                   │
│                                                              │
│  Return: list[TradingSignal]                                 │
└─────────────────────────────────────────────────────────────┘
     │
     ▼
Discord / Notification layer

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
STRATEGY VERDICTS
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Each strategy produces a StrategyVerdict:
  direction  : "BUY" | "SELL" | "NEUTRAL"
  confidence : 0.0 – 1.0  (strategy's own score)
  reason     : plain-English explanation
  active     : False if the strategy found no valid setup (skip from voting)

Only strategies with active=True participate in the vote.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
CONFLUENCE LOGIC
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

For each TradeIdea generated by the SMC strategy:
  1. The SMC idea's direction is the "candidate direction."
  2. We ask Trend and LiqSweep strategies:
     "Does your verdict match this direction?"
  3. Count matching strategies → confluence_count.
  4. Any active strategy voting the OPPOSITE direction triggers rejection.

Boost schedule:
  confluence_count == 1 (SMC alone)             →  ± 0     (no bonus)
  confluence_count == 2 (SMC + one other)        →  +0.08
  confluence_count == 3 (all three agree)         →  +0.15

Rejection on conflict:
  Any OTHER active strategy voting opposite direction → rejected
  at "strategy_conflict" stage.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
CONFIDENCE SCORING (all deltas)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

  Component                  Weight / Delta    Trigger
  ─────────────────────────  ───────────────   ─────────────────
  SMC base score             0.0 – 1.0         from TradeIdea.confidence
  Confluence  (2 strategies) +0.08             trend OR liq agrees
  Confluence  (3 strategies) +0.15             both trend AND liq agree
  Trend alignment            +0.10             H1 trend matches direction
  Trend strength             +0.00 to +0.08   pro-rata on TrendResult.strength
  Regime: TRENDING           +0.05             market is directional
  Regime: RANGING            -0.15             choppy — SMC unreliable
  Regime: HIGH_VOLATILITY    -0.10             OBs unstable
  Session: overlap           +0.10             best execution window
  Session: london            +0.05             high institutional flow
  Session: new_york          +0.03             USD-driven volatility
  Session: asian             -0.10             low gold liquidity
  Volatility: optimal ATR    +0.05             ideal range for setups
  Volatility: too high       -0.15             news spike risk
  Volatility: too low        -0.10             choppy / dead market
  Liquidity sweep match      +0.05             liq sweep confirms idea dir
  Liquidity sweep opposite   -0.10             liq sweep contradicts dir
  OB + FVG overlap           +0.05             two SMC signals overlap
  News: blackout             hard reject       near high-impact event

Final confidence clamped to [0.0, 1.0].
Signal published only if final_confidence >= cfg.CONFIDENCE_THRESHOLD.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
PUBLIC API
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  sg = SignalGenerator(settings)
  signals, rejects = sg.generate(df_h1, df_m15, account_balance=10_000)

  # Or validate a single idea (e.g., from backtester)
  result = sg.generate_from_idea(idea, df_m15, account_balance=10_000,
                                 trend_result=tr, regime_label=rl)

Dependencies
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  strategy.SmartMoneyStrategy, strategy.TrendDetector,
  strategy.market_regime.MarketRegimeClassifier,
  strategy.liquidity_detection.LiquiditySweepDetector,
  strategy.liquidity_map.LiquidityMapper,       (optional)
  risk.PositionSizer, filters.*,
  config.settings.Settings, utils.logger
"""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime, timezone
from typing import Optional

import pandas as pd

from config.settings import Settings
from filters.news_filter import NewsFilter
from filters.session_filter import SessionFilter
from filters.volatility_filter import VolatilityFilter
from risk.position_sizing import PositionSizer, PositionSize
from strategy.market_regime import MarketRegimeClassifier, RegimeLabel
from strategy.smart_money_strategy import SmartMoneyStrategy, TradeIdea
from strategy.trend_detection import TrendDetector, TrendDirection, TrendResult
from strategy.liquidity_detection import LiquiditySweepDetector, LiquiditySweep
from utils.logger import get_logger, TradingDebugLogger

logger     = get_logger(__name__)
_dbg_log   = TradingDebugLogger()    # shared instance for this module


# Optional imports — gracefully degrade if not present
try:
    from strategy.liquidity_map import LiquidityMapper, LiquidityMap
    _LIQUIDITY_MAP_AVAILABLE = True
except ImportError:
    _LIQUIDITY_MAP_AVAILABLE = False
    LiquidityMapper = None
    LiquidityMap    = None


# ─────────────────────────────────────────────────────────────────────────────
# Strategy verdict — result from a single strategy sub-engine
# ─────────────────────────────────────────────────────────────────────────────

@dataclass
class StrategyVerdict:
    """
    The opinion of one strategy sub-engine on the current market.

    Used by the multi-strategy confluence engine to combine views.

    Attributes
    ----------
    strategy_name : Human-readable name ("TREND" | "SMC" | "LIQUIDITY_SWEEP")
    direction     : "BUY" | "SELL" | "NEUTRAL"
    confidence    : 0.0 – 1.0 — the strategy's own certainty score
    active        : True if the strategy found a valid setup.
                    False = no setup detected (strategy abstains from voting)
    reason        : Plain-English explanation of the verdict
    """
    strategy_name: str
    direction:     str     = "NEUTRAL"
    confidence:    float   = 0.0
    active:        bool    = False
    reason:        str     = ""

    @property
    def is_buy(self)  -> bool: return self.active and self.direction == "BUY"
    @property
    def is_sell(self) -> bool: return self.active and self.direction == "SELL"

    def __str__(self) -> str:
        flag = "✅" if self.active else "⬜"
        return (
            f"{flag} {self.strategy_name:<18} "
            f"dir={self.direction:<7} "
            f"conf={self.confidence:.0%}  "
            f"{self.reason[:55]}"
        )


# ─────────────────────────────────────────────────────────────────────────────
# Confluence result
# ─────────────────────────────────────────────────────────────────────────────

@dataclass
class ConfluenceResult:
    """
    Summary of multi-strategy confluence analysis for one trade direction.

    Attributes
    ----------
    direction          : Candidate direction ("BUY" or "SELL")
    total_active       : Number of strategies that produced an active verdict
    agreeing           : Count of active strategies agreeing with direction
    conflicting        : Count of active strategies opposing direction
    conflict_detected  : True if any active strategy voted opposite direction
    confluence_boost   : Confidence delta to apply (0.0 / +0.08 / +0.15)
    verdicts           : All StrategyVerdicts (for transparency / logging)
    """
    direction:         str
    total_active:      int   = 0
    agreeing:          int   = 0
    conflicting:       int   = 0
    conflict_detected: bool  = False
    confluence_boost:  float = 0.0
    verdicts:          list[StrategyVerdict] = field(default_factory=list)

    def summary_str(self) -> str:
        agree_names    = [v.strategy_name for v in self.verdicts if v.active and v.direction == self.direction]
        conflict_names = [v.strategy_name for v in self.verdicts if v.active and v.direction != self.direction and v.direction != "NEUTRAL"]
        parts = []
        if agree_names:
            parts.append(f"agree=[{', '.join(agree_names)}]")
        if conflict_names:
            parts.append(f"CONFLICT=[{', '.join(conflict_names)}]")
        boost_str = f"boost={self.confluence_boost:+.0%}" if self.confluence_boost else "boost=none"
        return f"{self.direction} {boost_str} active={self.total_active} {' '.join(parts)}"


# ─────────────────────────────────────────────────────────────────────────────
# Output dataclass — TradingSignal (unchanged API)
# ─────────────────────────────────────────────────────────────────────────────

@dataclass
class TradingSignal:
    """
    A fully validated, publication-ready trading signal.

    All fields are populated before the signal is emitted to Telegram.
    The to_dict() method produces the machine-readable version.
    """
    # ── Identity ──────────────────────────────────────────────────────────────
    symbol:    str
    direction: str                        # "BUY" | "SELL"
    timestamp: datetime = field(default_factory=lambda: datetime.now(timezone.utc))

    # ── Trade levels ──────────────────────────────────────────────────────────
    entry_price:   float = 0.0
    stop_loss:     float = 0.0
    take_profit_1: float = 0.0
    take_profit_2: Optional[float] = None

    # ── Risk / sizing ─────────────────────────────────────────────────────────
    lot_size:           float = 0.0
    risk_amount_usd:    float = 0.0
    risk_pct:           float = 0.0
    rr_ratio_tp1:       Optional[float] = None
    rr_ratio_tp2:       Optional[float] = None
    monetary_value_1pt: float = 0.0

    # ── Scores ────────────────────────────────────────────────────────────────
    confidence:     float = 0.0           # final composite score [0, 1]
    smc_confidence: float = 0.0           # raw SMC score before adjustments
    trend_strength: float = 0.0           # TrendResult.strength

    # ── Context ───────────────────────────────────────────────────────────────
    regime:          str = ""             # RegimeLabel.value
    session:         str = ""             # "london" | "new_york" | ...
    trend_direction: str = ""             # "BULLISH" | "BEARISH" | "NEUTRAL"

    # ── SMC evidence flags ────────────────────────────────────────────────────
    has_ob:              bool = False
    has_fvg:             bool = False
    has_bos:             bool = False
    has_choch:           bool = False
    has_liquidity_sweep: bool = False

    # ── Multi-strategy confluence (new) ───────────────────────────────────────
    confluence_count:   int   = 0         # how many strategies agreed
    confluence_boost:   float = 0.0       # boost applied to confidence
    strategy_verdicts:  list  = field(default_factory=list)   # list[StrategyVerdict]

    # ── Confidence breakdown (for transparency / logs) ────────────────────────
    confidence_breakdown: dict = field(default_factory=dict)

    # ── Raw idea reference (for debugging) ────────────────────────────────────
    notes: str = ""

    # =========================================================================
    # OUTPUT HELPERS
    # =========================================================================

    def to_dict(self) -> dict:
        """Return a machine-readable dict for signal logging and Telegram formatting."""
        def r(v, d=2):
            return round(v, d) if v is not None else None

        return {
            "symbol":            self.symbol,
            "direction":         self.direction,
            "timestamp":         self.timestamp.isoformat(),
            "entry_price":       r(self.entry_price),
            "stop_loss":         r(self.stop_loss),
            "take_profit_1":     r(self.take_profit_1),
            "take_profit_2":     r(self.take_profit_2),
            "lot_size":          r(self.lot_size),
            "risk_amount_usd":   r(self.risk_amount_usd),
            "risk_pct":          r(self.risk_pct),
            "rr_ratio_tp1":      r(self.rr_ratio_tp1),
            "rr_ratio_tp2":      r(self.rr_ratio_tp2),
            "confidence":        r(self.confidence, 3),
            "smc_confidence":    r(self.smc_confidence, 3),
            "trend_strength":    r(self.trend_strength, 3),
            "regime":            self.regime,
            "session":           self.session,
            "trend_direction":   self.trend_direction,
            "has_ob":            self.has_ob,
            "has_fvg":           self.has_fvg,
            "has_bos":           self.has_bos,
            "has_choch":         self.has_choch,
            "has_liquidity_sweep": self.has_liquidity_sweep,
            "confluence_count":  self.confluence_count,
            "confluence_boost":  r(self.confluence_boost, 3),
            "notes":             self.notes,
        }



    def __str__(self) -> str:
        return (
            f"TradingSignal({self.direction} {self.symbol} | "
            f"E={self.entry_price:.2f} SL={self.stop_loss:.2f} "
            f"TP={self.take_profit_1:.2f} | "
            f"lot={self.lot_size:.2f} risk=${self.risk_amount_usd:.0f} | "
            f"conf={self.confidence:.0%} confluence={self.confluence_count} | "
            f"sess={self.session} regime={self.regime})"
        )


# ─────────────────────────────────────────────────────────────────────────────
# Rejection record
# ─────────────────────────────────────────────────────────────────────────────

@dataclass
class RejectedIdea:
    """A TradeIdea that was rejected during validation, with the reason."""
    idea:      TradeIdea
    reason:    str
    stage:     str    # which gate rejected it


# ─────────────────────────────────────────────────────────────────────────────
# Multi-strategy decision engine
# ─────────────────────────────────────────────────────────────────────────────

# Confluence boost table: n_agreeing_strategies → confidence_delta
_CONFLUENCE_BOOST: dict[int, float] = {
    0:  0.00,
    1:  0.00,   # base SMC only — no bonus
    2: +0.08,   # one corroborating strategy
    3: +0.15,   # all three agree — maximum conviction
}


class SignalGenerator:
    """
    Multi-strategy orchestrator for the AntiGravity Gold Bot.

    Runs three independent strategy engines, combines their verdicts via a
    confluence vote, then validates each passing idea through a strict
    multi-gate filter chain.

    Three strategies
    ────────────────
    A. Trend Strategy     — EMA 50/200 crossover + slope + price position
    B. SMC Strategy       — Order blocks, FVGs, BOS, CHoCH, liquidity pools
    C. Liquidity Sweep    — Stop-hunt detection (sweep + reverse pattern)

    Confluence rules
    ────────────────
    • All 3 agree   → +0.15 boost
    • Any 2 agree   → +0.08 boost
    • Only SMC      →  no bonus
    • Any conflict  → REJECT (active strategies cannot disagree on direction)

    The SMC strategy is the primary signal source — it generates the
    candidate TradeIdeas.  Trend and LiqSweep are corroborators that boost
    or block each idea.

    Usage
    ─────
        sg = SignalGenerator(settings)
        signals, rejects = sg.generate(df_h1, df_m15, account_balance=10_000)
    """

    def __init__(
        self,
        settings:           Settings,
        news_filter:        Optional[NewsFilter]        = None,
        session_filter:     Optional[SessionFilter]     = None,
        volatility_filter:  Optional[VolatilityFilter]  = None,
        use_liquidity_map:  bool                        = True,
    ) -> None:
        """
        Parameters
        ----------
        settings            : App configuration (risk, session, ATR, R:R thresholds)
        news_filter         : If None, safe_mode=True is used (no live API)
        session_filter      : If None, constructed from settings
        volatility_filter   : If None, constructed from settings
        use_liquidity_map   : Whether to use LiquidityMapper for TP/entry guard
                              (requires strategy.liquidity_map module)
        """
        self.cfg = settings

        # ── Strategy sub-engines ──────────────────────────────────────────────
        self.trend_detector  = TrendDetector(
            slow_period  = settings.EMA_SLOW_PERIOD,
            macro_period = settings.EMA_MACRO_PERIOD,
        )
        self.regime_clf   = MarketRegimeClassifier(settings)
        self.smc          = SmartMoneyStrategy(settings)
        self.liq_detector = LiquiditySweepDetector(settings)
        self.sizer        = PositionSizer(settings)

        # Optional liquidity map
        self._use_liq_map = use_liquidity_map and _LIQUIDITY_MAP_AVAILABLE
        self.liq_mapper   = LiquidityMapper(settings) if self._use_liq_map else None

        # ── Filters ──────────────────────────────────────────────────────────
        self.session_f    = session_filter    or SessionFilter(settings)
        self.volatility_f = volatility_filter or VolatilityFilter(settings)
        self.news_f       = news_filter       or NewsFilter(settings, safe_mode=True)

        # ── Daily signal tracking ─────────────────────────────────────────────
        self._signals_today:     list[TradingSignal] = []
        self._last_reset_date:   Optional[datetime]  = None

    # =========================================================================
    # PRIMARY PUBLIC API
    # =========================================================================

    def generate(
        self,
        df_h1:           pd.DataFrame,
        df_m15:          pd.DataFrame,
        account_balance: float,
        df_m5:           Optional[pd.DataFrame] = None,
        now:             Optional[datetime]      = None,
    ) -> tuple[list[TradingSignal], list[RejectedIdea]]:
        """
        Run the full multi-strategy signal generation pipeline.

        Parameters
        ----------
        df_h1           : H1 OHLCV — trend + regime context
        df_m15          : M15 OHLCV — SMC scan + liq sweep
        account_balance : Live equity for lot sizing (USD)
        df_m5           : Optional fine-grained data (reserved for future use)
        now             : Override current UTC datetime (for testing)

        Returns
        -------
        (signals: list[TradingSignal], rejected: list[RejectedIdea])
        """
        now = now or datetime.now(timezone.utc)
        self._reset_daily_counter(now)

        signals:  list[TradingSignal] = []
        rejected: list[RejectedIdea]  = []

        # ── Step 1: Pre-scan gate ─────────────────────────────────────────────
        _dbg_log.cycle_start(now)

        sess_ok,  sess_reason = self.session_f.is_allowed(now)
        vol_ok,   vol_reason  = self.volatility_f.is_allowed(df_m15)
        news_ok,  news_reason = self.news_f.is_allowed(now)

        _dbg_log.pre_scan_filters(
            sess_ok, sess_reason,
            vol_ok,  vol_reason,
            news_ok, news_reason,
        )

        if not sess_ok:
            logger.info(f"SignalGenerator: pre-scan BLOCKED — session: {sess_reason}")
        if not vol_ok:
            logger.info(f"SignalGenerator: pre-scan BLOCKED — volatility: {vol_reason}")
        if not news_ok:
            logger.info(f"SignalGenerator: pre-scan BLOCKED — news: {news_reason}")

        hard_block = (not sess_ok) and (not vol_ok)
        if hard_block:
            logger.info("SignalGenerator: hard-block active — skipping scans")
            _dbg_log.cycle_summary(signals, rejected)
            return signals, rejected

        # ── Step 2: Shared context (runs ONCE) ───────────────────────────────
        trend_result  = self._get_trend(df_h1)
        regime_result = self._get_regime(df_h1)
        liq_sweep     = self._get_liquidity_sweep(df_m15)

        _dbg_log.context(trend_result, regime_result, liq_sweep)

        logger.info(
            f"SignalGenerator: "
            f"trend={trend_result.direction.value}({trend_result.strength:.0%})  "
            f"regime={regime_result.regime.value}  "
            f"liq_sweep={'YES' if liq_sweep else 'none'}"
        )

        # ── Step 3: Get strategy verdicts ─────────────────────────────────────
        trend_verdict = self._run_trend_strategy(trend_result)
        liq_verdict   = self._run_liq_sweep_strategy(liq_sweep)

        _dbg_log.strategy_verdicts([trend_verdict, liq_verdict])

        logger.info(
            f"Strategy verdicts:\n"
            f"  {trend_verdict}\n"
            f"  {liq_verdict}"
        )

        # ── Step 4: SMC scan — produces candidate ideas ───────────────────────
        raw_ideas = self._scan_smc(df_m15)

        if not raw_ideas:
            logger.info("SignalGenerator: SMC scan — no raw ideas")
            _dbg_log.smc_ideas([])
            _dbg_log.cycle_summary(signals, rejected)
            return signals, rejected

        _dbg_log.smc_ideas(raw_ideas)
        logger.info(f"SignalGenerator: {len(raw_ideas)} raw SMC idea(s)")

        # ── Step 5: Per-idea confluence + validation ──────────────────────────
        for idea_num, idea in enumerate(raw_ideas, 1):

            _dbg_log.idea_start(idea_num, idea)

            # ── 5a: Confluence vote ───────────────────────────────────────────
            smc_verdict    = self._build_smc_verdict(idea)
            confluence     = self._compute_confluence(
                idea.direction, smc_verdict, trend_verdict, liq_verdict
            )

            _dbg_log.confluence(idea.direction, confluence)
            logger.debug(f"  Confluence: {confluence.summary_str()}")

            # Conflict → hard reject
            if confluence.conflict_detected:
                reject_reason = (
                    f"Strategy conflict on {idea.direction}: "
                    f"{confluence.agreeing} agree, "
                    f"{confluence.conflicting} conflict. "
                    f"{confluence.summary_str()}"
                )
                rejected.append(RejectedIdea(
                    idea   = idea,
                    reason = reject_reason,
                    stage  = "strategy_conflict",
                ))
                _dbg_log.gate_reject("strategy_conflict", reject_reason, idea)
                logger.debug(f"  ❌ Rejected (conflict): {idea.direction}")
                continue

            # ── 5b: Full validation gate chain ───────────────────────────────
            result = self.generate_from_idea(
                idea             = idea,
                df_m15           = df_m15,
                account_balance  = account_balance,
                trend_result     = trend_result,
                regime_label     = regime_result.regime,
                sess_ok          = sess_ok,
                vol_ok           = vol_ok,
                news_ok          = news_ok,
                now              = now,
                confluence       = confluence,
            )

            if isinstance(result, TradingSignal):
                signals.append(result)
                self._signals_today.append(result)
                _dbg_log.signal_approved(result)
                logger.info(
                    f"SignalGenerator: APPROVED — {result}  "
                    f"confluence={result.confluence_count}/3"
                )

            elif isinstance(result, RejectedIdea):
                rejected.append(result)
                logger.debug(
                    f"SignalGenerator: REJECTED [{result.stage}] — {result.reason}"
                )

        _dbg_log.cycle_summary(signals, rejected)
        logger.info(
            f"SignalGenerator: cycle done — "
            f"{len(signals)} approved, {len(rejected)} rejected"
        )
        return signals, rejected

    def generate_from_idea(
        self,
        idea:            TradeIdea,
        df_m15:          pd.DataFrame,
        account_balance: float,
        trend_result:    Optional[TrendResult]      = None,
        regime_label:    Optional[RegimeLabel]      = None,
        sess_ok:         bool                       = True,
        vol_ok:          bool                       = True,
        news_ok:         bool                       = True,
        now:             Optional[datetime]         = None,
        confluence:      Optional[ConfluenceResult] = None,
    ) -> TradingSignal | RejectedIdea:
        """
        Validate a single TradeIdea through all gates and return a TradingSignal.

        This is also the entry point used by the backtesting engine.
        `confluence` may be None (e.g., when called from backtester), in which
        case a neutral ConfluenceResult is assumed (zero boost).

        Returns TradingSignal on success, RejectedIdea on any gate failure.
        """
        now = now or datetime.now(timezone.utc)

        # ── Gate 1: News blackout (hard reject) ──────────────────────────────
        if not news_ok:
            _dbg_log.gate_reject("news_filter", "News blackout active", idea)
            return RejectedIdea(
                idea   = idea,
                reason = "News blackout active",
                stage  = "news_filter",
            )

        # ── Gate 2: Trend alignment ───────────────────────────────────────────
        if trend_result is None:
            trend_result = TrendResult()

        trend_aligned = trend_result.allows_direction(idea.direction)
        if not trend_aligned and trend_result.direction not in (
            TrendDirection.NEUTRAL, TrendDirection.UNKNOWN
        ):
            reason = (
                f"Trend misalignment: signal={idea.direction}, "
                f"trend={trend_result.direction.value}"
            )
            _dbg_log.gate_reject("trend_alignment", reason, idea)
            return RejectedIdea(
                idea   = idea,
                reason = reason,
                stage  = "trend_alignment",
            )
        _dbg_log.gate_pass(
            "trend_alignment",
            f"signal={idea.direction} trend={trend_result.direction.value}",
        )

        # ── Gate 3: Regime suitability ────────────────────────────────────────
        if regime_label in (RegimeLabel.RANGING, RegimeLabel.LOW_VOLATILITY):
            if idea.confidence < 0.65:
                reason = (
                    f"Regime={regime_label.value} with low SMC "
                    f"confidence ({idea.confidence:.0%} < 0.65)"
                )
                _dbg_log.gate_reject("regime_gate", reason, idea)
                return RejectedIdea(
                    idea   = idea,
                    reason = reason,
                    stage  = "regime_gate",
                )
        _dbg_log.gate_pass(
            "regime_gate",
            regime_label.value if regime_label else "N/A",
        )

        # ── Step 4: Confidence rescoring ──────────────────────────────────────
        if confluence is None:
            confluence = ConfluenceResult(direction=idea.direction, agreeing=1)

        final_confidence, breakdown = self._rescore_confidence(
            base_score   = idea.confidence,
            idea         = idea,
            trend_result = trend_result,
            regime_label = regime_label,
            df_m15       = df_m15,
            sess_ok      = sess_ok,
            vol_ok       = vol_ok,
            news_ok      = news_ok,
            now          = now,
            confluence   = confluence,
        )

        _dbg_log.confidence_breakdown(
            base      = idea.confidence,
            breakdown = breakdown,
            final     = final_confidence,
            threshold = self.cfg.CONFIDENCE_THRESHOLD,
        )

        # ── Gate 5: Minimum confidence ────────────────────────────────────────
        if final_confidence < self.cfg.CONFIDENCE_THRESHOLD:
            reason = (
                f"Confidence {final_confidence:.0%} < "
                f"threshold {self.cfg.CONFIDENCE_THRESHOLD:.0%}"
            )
            _dbg_log.gate_reject("confidence_threshold", reason, idea)
            return RejectedIdea(
                idea   = idea,
                reason = reason,
                stage  = "confidence_threshold",
            )
        _dbg_log.gate_pass(
            "confidence_threshold",
            f"{final_confidence:.1%} ≥ {self.cfg.CONFIDENCE_THRESHOLD:.1%}",
        )

        # ── Step 6: Position sizing ───────────────────────────────────────────
        try:
            sizing = self.sizer.calculate(
                entry_price     = idea.entry,
                stop_loss       = idea.stop_loss,
                take_profit_1   = idea.take_profit,
                take_profit_2   = idea.take_profit_2,
                account_balance = account_balance,
            )
        except Exception as exc:
            _dbg_log.gate_reject("position_sizing", str(exc), idea)
            return RejectedIdea(
                idea   = idea,
                reason = f"Position sizing failed: {exc}",
                stage  = "position_sizing",
            )

        # ── Gate 7: R:R threshold ─────────────────────────────────────────────
        rr = sizing.rr_ratio_tp1 or 0.0
        if rr < self.cfg.MIN_RR_RATIO:
            reason = f"R:R {rr:.2f} < minimum {self.cfg.MIN_RR_RATIO:.1f}:1"
            _dbg_log.gate_reject("rr_ratio", reason, idea)
            return RejectedIdea(
                idea   = idea,
                reason = reason,
                stage  = "rr_ratio",
            )
        _dbg_log.gate_pass("rr_ratio", f"R:R {rr:.2f} ≥ {self.cfg.MIN_RR_RATIO:.1f}")

        # ── Step 8: Assemble TradingSignal ────────────────────────────────────
        session = self.session_f.current_session(now)
        signal  = TradingSignal(
            symbol              = self.cfg.SYMBOL,
            direction           = idea.direction,
            timestamp           = now,
            entry_price         = idea.entry,
            stop_loss           = idea.stop_loss,
            take_profit_1       = idea.take_profit,
            take_profit_2       = idea.take_profit_2,
            lot_size            = sizing.lot_size,
            risk_amount_usd     = sizing.risk_amount_usd,
            risk_pct            = sizing.actual_risk_pct,
            rr_ratio_tp1        = sizing.rr_ratio_tp1,
            rr_ratio_tp2        = sizing.rr_ratio_tp2,
            monetary_value_1pt  = sizing.monetary_value_1pt,
            confidence          = round(final_confidence, 3),
            smc_confidence      = round(idea.confidence, 3),
            trend_strength      = round(trend_result.strength, 3),
            regime              = regime_label.value if regime_label else "",
            session             = session,
            trend_direction     = trend_result.direction.value,
            has_ob              = idea.has_ob,
            has_fvg             = idea.has_fvg,
            has_bos             = idea.has_bos,
            has_choch           = idea.has_choch,
            has_liquidity_sweep = idea.has_liquidity_sweep,
            confluence_count    = confluence.agreeing,
            confluence_boost    = confluence.confluence_boost,
            strategy_verdicts   = confluence.verdicts,
            confidence_breakdown = breakdown,
            notes               = idea.notes,
        )
        return signal

    # =========================================================================
    # STRATEGY SUB-ENGINES
    # =========================================================================

    def _run_trend_strategy(self, trend_result: TrendResult) -> StrategyVerdict:
        """
        Strategy A: Trend Strategy verdict.

        Logic
        -----
        • BULLISH trend (direction=BULLISH, strength > 0.30) → BUY verdict
        • BEARISH trend (direction=BEARISH, strength > 0.30) → SELL verdict
        • NEUTRAL / UNKNOWN / strength ≤ 0.30               → NEUTRAL (abstain)

        The strength threshold ensures the trend is meaningful — weak or
        oscillating EMAs don't produce a directional opinion.
        """
        MIN_TREND_STRENGTH = 0.30

        if (trend_result.direction == TrendDirection.BULLISH
                and trend_result.strength >= MIN_TREND_STRENGTH):
            return StrategyVerdict(
                strategy_name = "TREND",
                direction     = "BUY",
                confidence    = round(trend_result.strength, 3),
                active        = True,
                reason        = (
                    f"BULLISH EMA structure  "
                    f"str={trend_result.strength:.0%}  "
                    f"EMA50={trend_result.ema_50:.2f}  "
                    f"EMA200={trend_result.ema_200:.2f}"
                ),
            )

        if (trend_result.direction == TrendDirection.BEARISH
                and trend_result.strength >= MIN_TREND_STRENGTH):
            return StrategyVerdict(
                strategy_name = "TREND",
                direction     = "SELL",
                confidence    = round(trend_result.strength, 3),
                active        = True,
                reason        = (
                    f"BEARISH EMA structure  "
                    f"str={trend_result.strength:.0%}  "
                    f"EMA50={trend_result.ema_50:.2f}  "
                    f"EMA200={trend_result.ema_200:.2f}"
                ),
            )

        return StrategyVerdict(
            strategy_name = "TREND",
            direction     = "NEUTRAL",
            confidence    = 0.0,
            active        = False,
            reason        = (
                f"No clear trend  "
                f"dir={trend_result.direction.value}  "
                f"str={trend_result.strength:.0%}"
            ),
        )

    def _run_liq_sweep_strategy(
        self, liq_sweep: Optional[LiquiditySweep]
    ) -> StrategyVerdict:
        """
        Strategy C: Liquidity Sweep Strategy verdict.

        Logic
        -----
        A CONFIRMED liquidity sweep is a directional signal:
          Sweep LOW  → BUY  (sell-side stops grabbed → institutions going long)
          Sweep HIGH → SELL (buy-side stops grabbed  → institutions going short)

        A LOW-quality sweep earns NEUTRAL (not strong enough to corroborate).
        No sweep at all → NEUTRAL (strategy abstains).
        """
        from strategy.liquidity_detection import SweepQuality

        if liq_sweep is None:
            return StrategyVerdict(
                strategy_name = "LIQUIDITY_SWEEP",
                direction     = "NEUTRAL",
                confidence    = 0.0,
                active        = False,
                reason        = "No recent liquidity sweep detected",
            )

        if liq_sweep.quality == SweepQuality.LOW:
            return StrategyVerdict(
                strategy_name = "LIQUIDITY_SWEEP",
                direction     = "NEUTRAL",
                confidence    = 0.0,
                active        = False,
                reason        = (
                    f"Sweep quality too low ({liq_sweep.quality.value}) — "
                    f"not corroborating"
                ),
            )

        return StrategyVerdict(
            strategy_name = "LIQUIDITY_SWEEP",
            direction     = liq_sweep.direction,   # "BUY" or "SELL"
            confidence    = round(liq_sweep.quality_score, 3),
            active        = True,
            reason        = (
                f"Sweep {liq_sweep.type.value}  "
                f"level={liq_sweep.sweep_price:.2f}  "
                f"wick={liq_sweep.wick_atr_ratio:.2f}×ATR  "
                f"quality={liq_sweep.quality.value}({liq_sweep.quality_score:.0%})  "
                f"{'CONFIRMED' if liq_sweep.confirmed else 'unconfirmed'}"
            ),
        )

    def _build_smc_verdict(self, idea: TradeIdea) -> StrategyVerdict:
        """
        Build a StrategyVerdict from a TradeIdea for use in the confluence vote.

        The SMC strategy is always active when a TradeIdea exists.
        """
        # Count SMC components present
        component_count = sum([
            idea.has_ob, idea.has_fvg, idea.has_bos,
            idea.has_choch, idea.has_liquidity_sweep,
        ])
        return StrategyVerdict(
            strategy_name = "SMC",
            direction     = idea.direction,
            confidence    = round(idea.confidence, 3),
            active        = True,
            reason        = (
                f"SMC setup  "
                f"conf={idea.confidence:.0%}  "
                f"components={component_count}  "
                f"{'OB ' if idea.has_ob else ''}"
                f"{'FVG ' if idea.has_fvg else ''}"
                f"{'BOS ' if idea.has_bos else ''}"
                f"{'CHoCH ' if idea.has_choch else ''}"
                f"{'Sweep' if idea.has_liquidity_sweep else ''}"
            ).strip(),
        )

    # =========================================================================
    # CONFLUENCE ENGINE
    # =========================================================================

    def _compute_confluence(
        self,
        candidate_direction: str,
        smc_verdict:         StrategyVerdict,
        trend_verdict:       StrategyVerdict,
        liq_verdict:         StrategyVerdict,
    ) -> ConfluenceResult:
        """
        Count how many active strategies agree / conflict on a candidate direction.

        Parameters
        ----------
        candidate_direction : "BUY" or "SELL" — direction proposed by the SMC idea
        smc_verdict         : SMC strategy verdict (always active here)
        trend_verdict       : Trend strategy verdict
        liq_verdict         : Liquidity sweep strategy verdict

        Returns
        -------
        ConfluenceResult with agreeing count, conflict flag, and boost.
        """
        all_verdicts = [smc_verdict, trend_verdict, liq_verdict]
        active       = [v for v in all_verdicts if v.active]

        agreeing    = 0
        conflicting = 0

        for v in active:
            if v.direction == candidate_direction:
                agreeing += 1
            elif v.direction != "NEUTRAL":
                conflicting += 1

        conflict_detected = conflicting > 0
        boost = _CONFLUENCE_BOOST.get(agreeing, 0.0) if not conflict_detected else 0.0

        logger.debug(
            f"  confluence({candidate_direction}): "
            f"active={len(active)} "
            f"agree={agreeing} "
            f"conflict={conflicting} "
            f"boost={boost:+.0%}"
        )

        return ConfluenceResult(
            direction         = candidate_direction,
            total_active      = len(active),
            agreeing          = agreeing,
            conflicting       = conflicting,
            conflict_detected = conflict_detected,
            confluence_boost  = boost,
            verdicts          = all_verdicts,
        )

    # =========================================================================
    # CONFIDENCE RESCORING
    # =========================================================================

    def _rescore_confidence(
        self,
        base_score:   float,
        idea:         TradeIdea,
        trend_result: TrendResult,
        regime_label: Optional[RegimeLabel],
        df_m15:       pd.DataFrame,
        sess_ok:      bool,
        vol_ok:       bool,
        news_ok:      bool,
        now:          datetime,
        confluence:   ConfluenceResult,
    ) -> tuple[float, dict]:
        """
        Adjust the raw SMC confidence score with all contextual and
        confluence factors.

        Returns (final_score: float, breakdown: dict).

        Breakdown keys:
          smc_base, confluence_boost, trend_alignment, trend_strength,
          regime_delta, session_delta, volatility_delta, news_delta,
          liq_sweep_delta, ob_fvg_overlap
        """
        score = base_score
        bd: dict[str, float] = {"smc_base": round(base_score, 3)}

        # ── Confluence boost ──────────────────────────────────────────────────
        score += confluence.confluence_boost
        bd["confluence_boost"] = confluence.confluence_boost

        # ── Trend alignment bonus ─────────────────────────────────────────────
        trend_dir = trend_result.direction
        if ((idea.direction == "BUY"  and trend_dir == TrendDirection.BULLISH) or
                (idea.direction == "SELL" and trend_dir == TrendDirection.BEARISH)):
            delta = +0.10
        elif trend_dir in (TrendDirection.NEUTRAL, TrendDirection.UNKNOWN):
            delta = 0.0
        else:
            delta = -0.08
        score += delta
        bd["trend_alignment"] = delta

        # ── Trend strength bonus (pro-rata 0–8%) ──────────────────────────────
        if ((trend_dir == TrendDirection.BULLISH and idea.direction == "BUY") or
                (trend_dir == TrendDirection.BEARISH and idea.direction == "SELL")):
            str_delta = trend_result.strength * 0.08
        else:
            str_delta = 0.0
        score += str_delta
        bd["trend_strength"] = round(str_delta, 3)

        # ── Regime delta ──────────────────────────────────────────────────────
        regime_delta = {
            RegimeLabel.TRENDING:        +0.05,
            RegimeLabel.RANGING:         -0.15,
            RegimeLabel.HIGH_VOLATILITY: -0.10,
            RegimeLabel.LOW_VOLATILITY:  -0.10,
        }.get(regime_label, 0.0)
        score += regime_delta
        bd["regime_delta"] = regime_delta

        # ── Session delta ─────────────────────────────────────────────────────
        sess_delta = self.session_f.confidence_delta(now)
        score += sess_delta
        bd["session_delta"] = sess_delta

        # ── Volatility delta ──────────────────────────────────────────────────
        vol_delta = self.volatility_f.confidence_delta(df_m15)
        score += vol_delta
        bd["volatility_delta"] = vol_delta

        # ── News delta (soft — news hard-blocks happen earlier) ───────────────
        news_delta = self.news_f.confidence_delta(now)
        score += news_delta
        bd["news_delta"] = news_delta

        # ── Liquidity sweep alignment bonus ───────────────────────────────────
        # If the liq sweep strategy was active and agrees → extra boost
        # (beyond the vote count — it's contextually very strong confirmation)
        liq_v = next(
            (v for v in confluence.verdicts if v.strategy_name == "LIQUIDITY_SWEEP"),
            None,
        )
        if liq_v and liq_v.active:
            if liq_v.direction == idea.direction:
                liq_delta = +0.05
            else:
                liq_delta = -0.10   # active sweep in opposite direction is notable
        else:
            liq_delta = 0.0
        score += liq_delta
        bd["liq_sweep_delta"] = liq_delta

        # ── OB + FVG overlap bonus ─────────────────────────────────────────────
        if idea.has_ob and idea.has_fvg:
            overlap_delta = +0.05
            score += overlap_delta
            bd["ob_fvg_overlap"] = overlap_delta

        # ── Clamp ─────────────────────────────────────────────────────────────
        final = round(min(max(score, 0.0), 1.0), 4)
        bd["final"] = final

        return final, bd

    # =========================================================================
    # INTERNAL HELPERS
    # =========================================================================

    def _get_trend(self, df_h1: pd.DataFrame) -> TrendResult:
        """Run TrendDetector on H1 data; return safe default on error."""
        try:
            return self.trend_detector.detect(df_h1)
        except Exception as exc:
            logger.warning(f"_get_trend() failed: {exc}")
            return TrendResult()

    def _get_regime(self, df_h1: pd.DataFrame):
        """Run MarketRegimeClassifier on H1 data; return safe default on error."""
        try:
            return self.regime_clf.classify(df_h1)
        except Exception as exc:
            logger.warning(f"_get_regime() failed: {exc}")
            from strategy.market_regime import RegimeResult
            return type("_DefaultRegime", (), {"regime": RegimeLabel.TRENDING})()

    def _get_liquidity_sweep(
        self, df_m15: pd.DataFrame
    ) -> Optional[LiquiditySweep]:
        """Run LiquiditySweepDetector; return the latest sweep or None."""
        try:
            return self.liq_detector.get_latest_sweep(df_m15)
        except Exception as exc:
            logger.warning(f"_get_liquidity_sweep() failed: {exc}")
            return None

    def _scan_smc(self, df: pd.DataFrame) -> list[TradeIdea]:
        """Run SmartMoneyStrategy scanner; return empty list on error."""
        try:
            return self.smc.scan(df)
        except Exception as exc:
            logger.error(f"_scan_smc() failed: {exc}")
            return []

    # =========================================================================
    # DAILY COUNTER
    # =========================================================================

    def _reset_daily_counter(self, now: datetime) -> None:
        """Reset the daily signal counter if the date has rolled over."""
        today = now.date()
        last  = self._last_reset_date.date() if self._last_reset_date else None
        if last != today:
            self._signals_today.clear()
            self._last_reset_date = now
            logger.info(f"SignalGenerator: daily counter reset for {today}")

    @property
    def signals_today(self) -> int:
        """Number of signals already dispatched today."""
        return len(self._signals_today)

    @property
    def daily_cap_reached(self) -> bool:
        """True if the daily signal cap has been hit."""
        return self.signals_today >= self.cfg.MAX_SIGNALS_PER_DAY

    # =========================================================================
    # REPR
    # =========================================================================

    def __repr__(self) -> str:
        return (
            f"SignalGenerator("
            f"symbol={self.cfg.SYMBOL}, "
            f"min_conf={self.cfg.CONFIDENCE_THRESHOLD:.0%}, "
            f"min_rr={self.cfg.MIN_RR_RATIO}, "
            f"max_daily={self.cfg.MAX_SIGNALS_PER_DAY}, "
            f"signals_today={self.signals_today}"
            f")"
        )
